import { describe, expect, it } from 'vitest';
import { DEFAULT_RECIPE } from '../../src/domain/presets';
import { parseRecipeText, serializeRecipe } from '../../src/domain/recipe';
import { importPrusaConfig } from '../../src/print/importProfile';
import { parseProjectText, serializeProject } from '../../src/print/project';
import { DEFAULT_PRINT_SETUP, getPrintSetupDiagnostics, parsePrintSetup } from '../../src/print/setup';

function setupCopy(): Record<string, unknown> {
  return structuredClone(DEFAULT_PRINT_SETUP) as unknown as Record<string, unknown>;
}

const FLATTENED_MINI_CONFIG = [
  '# generated by PrusaSlicer 2.9.1',
  'printer_model = MINIIS',
  'printer_settings_id = Original Prusa MINI+ 0.4 nozzle',
  'filament_settings_id = eSUN PLA Basic',
  'nozzle_diameter = 0.4',
  'filament_diameter = 1.75',
  'extrusion_multiplier = 1.03',
  'temperature = 208',
  'first_layer_temperature = 214',
  'bed_temperature = 58',
  'first_layer_bed_temperature = 60',
  'max_volumetric_speed = 4.8',
  'max_fan_speed = 95',
  'machine_max_feedrate_x = 90, 70',
  'machine_max_feedrate_y = 80, 60',
  'machine_max_feedrate_z = 7, 6',
  'machine_max_acceleration_x = 450, 400',
  'bed_shape = 0x0,180x0,180x180,0x180',
  'max_print_height = 180',
  'layer_height = 0.2',
  'extrusion_width = 0.45',
  'first_layer_height = 0.2',
  'start_gcode = G28 ; this remains unexecuted',
  'ordinary_slicer_setting = ignored',
].join('\n');

describe('print setup contract', () => {
  it('keeps explicit proposed MINI defaults and manual empty provenance', () => {
    expect(parsePrintSetup(DEFAULT_PRINT_SETUP)).toEqual(DEFAULT_PRINT_SETUP);
    expect(DEFAULT_PRINT_SETUP.printer.variant).toBe('unknown');
    expect(DEFAULT_PRINT_SETUP.provenance).toEqual({
      source: 'manual', filename: '', digest: '', slicerVersion: '', printerProfile: '', filamentProfile: '', importedValues: {}, mappedFields: [], ignoredFields: [], warnings: [],
    });
  });

  it.each([
    ['unknown field', (value: Record<string, unknown>) => { value.future = true; }, /unexpected field/],
    ['unknown schema', (value: Record<string, unknown>) => { value.schemaVersion = 99; }, /unsupported schemaVersion/],
    ['non-finite number', (value: Record<string, unknown>) => { ((value.material as Record<string, unknown>).nozzleC) = Number.NaN; }, /finite number/],
    ['unreviewed imported target', (value: Record<string, unknown>) => { ((value.provenance as Record<string, unknown>).importedValues) = { 'future.target': '1' }; }, /unsupported target/],
  ])('rejects $0 without silently changing it', (_label, mutate, message) => {
    const value = setupCopy();
    mutate(value);
    expect(() => parsePrintSetup(value)).toThrow(message);
  });

  it('allows a saved non-0.4 setup but blocks it at the narrow adapter boundary', () => {
    const value = setupCopy();
    (value.printer as Record<string, unknown>).nozzleDiameterMm = 0.6;
    expect(parsePrintSetup(value).printer.nozzleDiameterMm).toBe(0.6);
    expect(getPrintSetupDiagnostics(value)).toContainEqual(expect.objectContaining({ code: 'unsupported-nozzle', severity: 'error' }));
  });
});

describe('PrusaSlicer flattened config import', () => {
  it('maps bounded values, provenance, and named ignored settings without running macros', async () => {
    const result = await importPrusaConfig(FLATTENED_MINI_CONFIG, 'mini-export.ini', DEFAULT_PRINT_SETUP);

    expect(result.setup.printer.variant).toBe('unknown');
    expect(result.setup.printer.maxXySpeedMmS).toBe(60);
    expect(result.setup.printer.maxZSpeedMmS).toBe(6);
    expect(result.setup.printer.accelerationMmS2).toBe(400);
    expect(result.setup.material.nozzleC).toBe(208);
    expect(result.process).toEqual({ filamentDiameterMm: 1.75, flowMultiplier: 1.03 });
    expect(result.setup.provenance).toMatchObject({
      source: 'prusaslicer-config', filename: 'mini-export.ini', slicerVersion: '2.9.1',
      printerProfile: 'Original Prusa MINI+ 0.4 nozzle', filamentProfile: 'eSUN PLA Basic',
    });
    expect(result.setup.provenance.digest).toMatch(/^[a-f0-9]{64}$/);
    expect(result.setup.provenance.importedValues).toMatchObject({ 'material.nozzleC': '208', 'process.flowMultiplier': '1.03' });
    expect(result.setup.provenance.ignoredFields).toEqual(expect.arrayContaining(['start_gcode', 'ordinary_slicer_setting', 'first_layer_height']));
    expect(result.warnings).toEqual(expect.arrayContaining([
      expect.stringContaining('never executed'),
      expect.stringContaining('not represented'),
    ]));
  });

  it.each([
    ['vendor bundle section', '[printer:MINI]\nnozzle_diameter = 0.4', /vendor bundle section/],
    ['inheritance', 'inherits = base\nnozzle_diameter = 0.4', /unresolved profile field/],
    ['duplicate setting', 'nozzle_diameter = 0.4\nnozzle_diameter = 0.4', /Duplicate/],
    ['multi-extruder array', 'nozzle_diameter = 0.4,0.4', /arrays and expressions/],
    ['unknown printer', 'printer_model = MK4', /Unsupported printer_model/],
    ['percentage layer height', 'layer_height = 120%', /percentage value/],
    ['automatic width stays unresolved', 'extrusion_width = 0', /__success__/],
    ['wrong bed', 'bed_shape = 0x0,250x0,250x210,0x210', /Unsupported bed_shape/],
  ])('handles $0 explicitly', async (_label, text, error) => {
    if (error.source === '__success__') {
      const result = await importPrusaConfig(text, 'fixture.ini', DEFAULT_PRINT_SETUP);
      expect(result.setup.foundation.lineWidthMm).toBe(DEFAULT_PRINT_SETUP.foundation.lineWidthMm);
      expect(result.warnings).toEqual(expect.arrayContaining([expect.stringContaining('automatic width')]));
      return;
    }
    await expect(importPrusaConfig(text, 'fixture.ini', DEFAULT_PRINT_SETUP)).rejects.toThrow(error);
  });

  it('does not alter the supplied setup when a later mapped field is invalid', async () => {
    const current = structuredClone(DEFAULT_PRINT_SETUP);
    await expect(importPrusaConfig('temperature = 205\nmax_fan_speed = 101', 'broken.ini', current)).rejects.toThrow(/0 to 100/);
    expect(current).toEqual(DEFAULT_PRINT_SETUP);
  });

  it('does not carry source metadata from an earlier import into a later file', async () => {
    const first = await importPrusaConfig([
      '# generated by PrusaSlicer 2.8.0',
      'printer_model = MINI',
      'printer_settings_id = First MINI profile',
      'filament_settings_id = First PLA profile',
      'max_volumetric_speed = 4.4',
      'temperature = 206',
    ].join('\n'), 'first.ini', DEFAULT_PRINT_SETUP);
    const second = await importPrusaConfig([
      '# generated by PrusaSlicer 2.9.2',
      'printer_model = MINI',
      'temperature = 209',
    ].join('\n'), 'second.ini', first.setup);

    expect(first.setup.provenance).toMatchObject({ filename: 'first.ini', slicerVersion: '2.8.0', printerProfile: 'First MINI profile', filamentProfile: 'First PLA profile' });
    expect(second.setup.provenance).toMatchObject({ filename: 'second.ini', slicerVersion: '2.9.2', printerProfile: '', filamentProfile: '' });
    expect(second.setup.provenance.digest).not.toBe(first.setup.provenance.digest);
    expect(second.setup.material).toMatchObject({ nozzleC: 209, maxFlowMm3S: 4.4 });
  });

  it('accepts a realistic-sized flattened export with empty compatibility selectors and aggregates unknown fields', async () => {
    const unknown = Array.from({ length: 350 }, (_, index) => `ordinary_setting_${index} = ${index}`).join('\n');
    const result = await importPrusaConfig([
      'printer_model = MINIIS',
      'compatible_printers_condition = ',
      'compatible_prints = ',
      'max_volumetric_speed = 0',
      'filament_max_volumetric_speed = 4.2',
      'machine_max_feedrate_x = 90, 70',
      'machine_max_feedrate_y = 80, 60',
      'machine_max_feedrate_z = 8, 6',
      'machine_max_acceleration_x = 500, 400',
      unknown,
    ].join('\n'), 'full-export.ini', DEFAULT_PRINT_SETUP);

    expect(result.setup.printer.variant).toBe('unknown');
    expect(result.setup.material.maxFlowMm3S).toBe(4.2);
    expect(result.setup.provenance.ignoredFields).toHaveLength(352);
    expect(result.warnings).toEqual(expect.arrayContaining([
      expect.stringContaining('Ignored 350 unsupported'),
      expect.stringContaining('no print-profile cap'),
      expect.stringContaining('Consolidated normal/quiet'),
    ]));
  });
});

describe('project envelope', () => {
  it('round-trips recipe and setup while the recipe format remains unchanged', () => {
    const project = { format: 'np3dp-project' as const, schemaVersion: 2 as const, recipe: DEFAULT_RECIPE, setup: DEFAULT_PRINT_SETUP };
    const serialized = serializeProject(project);
    expect(parseProjectText(serialized)).toEqual(project);
    expect(serializeRecipe(parseProjectText(serialized).recipe)).toBe(serializeRecipe(DEFAULT_RECIPE));
    expect(parseRecipeText(serializeRecipe(DEFAULT_RECIPE))).toEqual(DEFAULT_RECIPE);
  });

  it('rejects a future project envelope without accepting unknown persisted semantics', () => {
    const future = JSON.parse(serializeProject({ format: 'np3dp-project', schemaVersion: 2, recipe: DEFAULT_RECIPE, setup: DEFAULT_PRINT_SETUP })) as Record<string, unknown>;
    future.schemaVersion = 99;
    expect(() => parseProjectText(JSON.stringify(future))).toThrow(/unsupported schemaVersion/);
  });

  it('migrates version 1 with zero compensation, preserving its original footprint', () => {
    const legacy = setupCopy();
    legacy.schemaVersion = 1;
    delete (legacy.foundation as Record<string, unknown>).elephantFootMm;
    const migrated = parseProjectText(JSON.stringify({ format: 'np3dp-project', schemaVersion: 1, recipe: DEFAULT_RECIPE, setup: legacy }));
    expect(migrated.schemaVersion).toBe(2);
    expect(migrated.setup.schemaVersion).toBe(2);
    expect(migrated.setup.foundation.elephantFootMm).toBe(0);
    expect(migrated.recipe).toEqual(DEFAULT_RECIPE);
    expect(parseProjectText(serializeProject(migrated))).toEqual(migrated);
    expect(() => parseProjectText(JSON.stringify({ ...migrated, schemaVersion: 1 }))).toThrow(/schema versions must match/);
  });

  it('imports explicit compensation with provenance and rejects an out-of-range inset', async () => {
    const imported = await importPrusaConfig('elefant_foot_compensation = 0.2', 'foot.ini', DEFAULT_PRINT_SETUP);
    expect(imported.setup.foundation.elephantFootMm).toBe(0.2);
    expect(imported.setup.provenance.importedValues['foundation.elephantFootMm']).toBe('0.2');
    await expect(importPrusaConfig('elefant_foot_compensation = 0.51', 'foot.ini', DEFAULT_PRINT_SETUP)).rejects.toThrow(/0 to 0.5/);
  });
});
